# Generated by Django 4.1.4 on 2023-04-15 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lowest_price', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variations',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('variation_text', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelparser.product')),
            ],
        ),
    ]
