# Generated by Django 4.1.4 on 2023-04-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelparser', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
