# Generated by Django 4.2 on 2023-04-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelparser', '0003_alter_variations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
